#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Copyright (C) Business Learning Incorporated (businesslearninginc.com)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License at
# <http://www.gnu.org/licenses/> for more details.
#
# -----------------------------------------------------------------------------
#
# Bash library (bash-lib) for general-purpose script processing
#

# -----------------------------------------------------------------------------
# check_program_dependencies() checks external program dependencies passed in
# through $0
#
check_program_dependencies() {

  for dep in "$@"; do

    if ! command -v "$dep" &>/dev/null; then
      printf "Error: program '%s' not installed.\n" "$dep" >&2
      quit 1
    fi

  done

}

# -----------------------------------------------------------------------------
# check_file_dependencies() checks file dependencies passed in through $0
#
check_file_dependencies() {

  for file in "$@"; do

    if [[ ! -f "$file" ]]; then
      printf "Error: file '%s' not found.\n" "$file" >&2
      quit 1
    fi

  done

}

# -----------------------------------------------------------------------------
# display_banner() builds and displays a custom-sized script banner using
# configuration details managed through the args library
#
display_banner() {

  cat <<-EOF

 |
 |  $(get_config_details title)
 |    $(get_config_details version)
 |
 |  Usage:
 |    $(get_config_details syntax)
 |
	EOF

  local max_col=0
  local arg_count
  arg_count=$(get_config_args_length)

  # Determine the maximum width needed for the arguments column for alignment
  for ((i = 0; i < arg_count; i++)); do
    local arg_string
    arg_string="$(get_config_arg "$i" short_form), $(get_config_arg "$i" long_form)"
    ((${#arg_string} > max_col)) && max_col=${#arg_string}
  done

  # Print the formatted arguments
  for ((i = 0; i < arg_count; i++)); do
    local arg
    local desc
    arg="$(get_config_arg "$i" short_form), $(get_config_arg "$i" long_form)"
    desc="$(get_config_arg "$i" description)"
    printf " |  %-*s  %s\n" "$max_col" "$arg" "$desc"
  done

  printf " |\n\n"

}

# -----------------------------------------------------------------------------
# function exist_directory() confirms directory existence
#
exist_directory() {

  if [[ ! -d "$1" ]]; then
    printf "Error: directory '%s' not found.\n" "$1" >&2
    quit 1
  fi

}

# -----------------------------------------------------------------------------
# quit() exits program (with exit status passed in)
#
quit() {
  exit "${1:-1}"
}
